# SPDX-License-Identifier: CC0-1.0
language = 'Zig'
display = 'Zig (Zig 0.14.0)'
license = [
    { name = 'MIT', url = 'https://github.com/ziglang/zig/blob/master/LICENSE' },
]

library.ac-library-zig = { license = [
    { name = 'CC0-1.0', url = 'https://github.com/Ryoga-exe/ac-library-zig/blob/main/LICENSE' },
], version = 'v0.2.0' }
library.proconio-zig = { license = [
    { name = 'MIT', url = 'https://github.com/Ryoga-exe/proconio-zig/blob/main/LICENSE' },
], version = 'v0.1.0' }
library.algorithms = { license = [
    { name = 'MIT', url = 'https://github.com/TheAlgorithms/Zig/blob/main/LICENSE' },
], version = '5b9cf67' }
library.zig-string = { license = [
    { name = 'MIT', url = 'https://github.com/JakubSzark/zig-string/blob/master/LICENSE' },
], version = 'f6f9e5dc7c5c45a72473de245a0e6958ef2bf913' }
library.ziter = { license = [
    { name = 'MIT', url = 'https://github.com/Hejsil/ziter/blob/master/LICENSE' },
], version = 'a1e61cb8d4f2a7ff882362ccb9108fe61d5e0c6f' }

filename = 'src/main.zig'

install = '''
AC_ZIG_VERSION=0.14.0
sudo apt-get update
sudo apt-get install -y --no-install-recommends git
pushd /tmp
wget -q https://ziglang.org/download/${AC_ZIG_VERSION}/zig-linux-x86_64-${AC_ZIG_VERSION}.tar.xz
sudo tar -C /opt -xf zig-linux-x86_64-${AC_ZIG_VERSION}.tar.xz
sudo ln -s /opt/zig-linux-x86_64-${AC_ZIG_VERSION}/zig /usr/local/bin/zig
popd

# Create Project
zig init
rm src/root.zig

# Install Libraries
zig fetch --save=ac-library git+https://github.com/Ryoga-exe/ac-library-zig#v0.2.0

zig fetch --save=proconio git+https://github.com/Ryoga-exe/proconio-zig#v0.1.0

zig fetch --save=string git+https://github.com/JakubSzark/zig-string#f6f9e5dc7c5c45a72473de245a0e6958ef2bf913

zig fetch --save=ziter git+https://github.com/Hejsil/ziter#8fc06df472ca99d902619807ad08034bc1bbe08e

cat << EOF > build.zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });

    const exe = b.addExecutable(.{
        .name = "judge",
        .root_module = exe_mod,
    });
    b.installArtifact(exe);

    const ac_library = b.dependency("ac-library", .{
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("ac-library", ac_library.module("ac-library"));

    const proconio = b.dependency("proconio", .{
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("proconio", proconio.module("proconio"));

    const string = b.dependency("string", .{
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("string", string.module("string"));

    const ziter = b.dependency("ziter", .{
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("ziter", ziter.module("ziter"));
}
EOF

mkdir src/algorithms
wget -q -O /tmp/algorithms.tar.gz https://github.com/TheAlgorithms/Zig/archive/5b9cf67.tar.gz
tar -C src/algorithms --strip-components=1 -xf /tmp/algorithms.tar.gz --wildcards '*/dataStructures' '*/dynamicProgramming' '*/math' '*/search' '*/sort'

cat << 'EOF' > src/main.zig
const std = @import("std");
const ac = @import("ac-library");
const iter = @import("ziter");

pub fn main() !void {
    const ascii_digits = try iter.range(u8, 0, 255)
        .filter({}, iter.void_ctx(std.ascii.isDigit))
        .collect_no_allocator(std.BoundedArray(u8, 255){});
    std.debug.print("{any}\n", .{ascii_digits.slice()});
    const allocator = std.heap.page_allocator;
    var d = try ac.Dsu.init(allocator, 10);
    defer d.deinit();
    _ = d.merge(0, 1);
    try std.testing.expect(d.same(0, 1));
    _ = d.merge(1, 5);
    var g = try d.groups();
    std.debug.print("{any}\n", .{g.get(0)});
}
EOF
zig build --release -Doptimize=ReleaseFast
./zig-out/bin/judge
rm zig-out/bin/judge
'''

compile = '''
zig build --release -Doptimize=ReleaseFast
'''

object = 'zig-out/bin/judge'

execution = ['./zig-out/bin/judge']
